"""Filenames under assets/ bundled into frozen (PyInstaller) builds.

Single source of truth for the compiler script and release checks.
Health-tier icons are merged from HEALTH_ICON_FILES so new tiers (e.g. cured.png)
cannot be forgotten in the build manifest.
"""
from __future__ import annotations

from steempeg.core.dash.health import HEALTH_ICON_FILES, WARNING_ICON_FILE

_BASE_ASSETS = (
    "logo.png",
    "logo.ico",
    "github.jpg",
    "steam.png",
    "icon_play.png",
    "icon_pause.png",
    "playmini.png",
    "less15.png",
    "more15.png",
    "unknown_icon.png",
    "copyfile.png",
    "theatremode.png",
    "theatremodeclosed.png",
    "trim_icon.png",
    "cancel.png",
    "linevolume.png",
    "btn_fullscreen.png",
    "kill.png",
    "knife.png",
    "nine.png",
    "one.png",
    "point.png",
    "restrict.png",
    "screenshot.png",
    "seven.png",
    "six.png",
    "smoke.png",
    "tazer.png",
    "three.png",
    "two.png",
    "zero.png",
    "bomb.png",
    "buttonvolume.png",
    "death.png",
    "defuse.png",
    "eight.png",
    "explosion.png",
    "firemolotov.png",
    "five.png",
    "flashbang.png",
    "four.png",
    "grenade.png",
    "scrollerhead2.png",
    "scrollerbody.png",
    "scrolleback.png",
    "saderror.png",
    "hideeye.png",
    "showeye.png",
    "multiplier.png",
    "dot.png",
    "clipcut1.png",
    "clipcut2.png",
    "pointuser.png",
    "clipcutback.png",
    "filter.png",
    "durationsort1.png",
    "durationsort2.png",
    "datesort1.png",
    "datesort2.png",
    "lettersort1.png",
    "lettersort2.png",
    "defaultsort.png",
    "camera.png",
    "buttonvolume1.png",
    "buttonvolume2.png",
    "buttonvolume3.png",
    "volumeoff.png",
    "health.png",
    "nohealth.png",
    "chupisuccess.png",
    "chupiwarn.png",
    "chupicutewarn.png",
    "history.png",
    "clear.png",
    "info.png",
    "arrow.png",
    "settings.png",
    "settings2.png",
    "desktop.png",
    "portable.png",
    "addclip.png",
    "queue.png",
)

_HEALTH_ASSETS = tuple(sorted({*HEALTH_ICON_FILES.values(), WARNING_ICON_FILE}))

BUNDLED_ASSET_FILES: tuple[str, ...] = _BASE_ASSETS + _HEALTH_ASSETS
